[package]
name = "bmk"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.28"
home = "0.5.11"
ratatui = "0.29"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
webbrowser = "1.0.5"

[dev-dependencies]
tempfile = "3.20.0"
